call plogdiff subst_test
call plogdiff equal_sub_test
call plogdiff equal_equiv_test
call plogdiff simple_q_test
call plogdiff free_test
call plogdiff mismatch_test
call plogdiff subproof_q_test
call plogdiff kaye_ch9_test
call plogdiff hr_ch2_test
call plogdiff back_test
call plogdiff backa_test
call plogdiff count_test
call plogdiff type_test
call plogdiff fol_apply_test
call plogdiff fol_save_test
