call plogdiff and_or_lr_reversed_test
call plogdiff and_test
call plogdiff and_wrong_indices_test
call plogdiff not_test
call plogdiff or_test
call plogdiff prop_contra_test
call plogdiff prop_raa_test
call plogdiff prop_test
call plogdiff top_test
call plogdiff prop_raa_scope_test
call plogdiff prop_f_or_scope_test
call plogdiff prop_constructive_test
call plogdiff prop_ore_scope_test
call plogdiff prop_derived_test
call plogdiff prop_apply_test
call plogdiff prop_save_test
